#!/usr/bin/python3
"""This module prints any one factorization of each number in a file"""
import sys
import time


def factorize(num):
    """Returns a pair of factors of a number"""

    if num % 2 == 0:
        return (2, num // 2)

    n = int(num**0.5)

    for x in range(3, n + 1, 2):
        if num % x == 0:
            return (x, num // x)

    return (1, num)


def main():
    """Prints any factorization of each number in a file"""

    if len(sys.argv) != 2:
        print("Usage: factors file")
        sys.exit(1)

    with open(sys.argv[1], 'r') as file:
        start = time.time()

        for line in file:
            num = int(line.rstrip("\n"))

            factors = factorize(num)
            print(f"{num}={factors[1]}*{factors[0]}")

            if time.time() - start > 5:
                print("Time limit exceeded")
                sys.exit(1)


if __name__ == "__main__":
    main()
